/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf8ff",
        "surface-dim": "#dcd8e5",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2fe",
        "surface-container": "#f0ecf9",
        "surface-container-high": "#eae6f3",
        "surface-container-highest": "#e4e1ed",
        "on-surface": "#1b1b23",
        "on-surface-variant": "#474555",
        "inverse-surface": "#302f39",
        "inverse-on-surface": "#f3effc",
        "outline": "#787586",
        "outline-variant": "#c8c4d7",
        "surface-tint": "#5544dc",
        "primary": "#5442db",
        "on-primary": "#ffffff",
        "primary-container": "#6d5ef5",
        "on-primary-container": "#fffdff",
        "inverse-primary": "#c5c0ff",
        "secondary": "#5c5697",
        "on-secondary": "#ffffff",
        "secondary-container": "#bdb6ff",
        "on-secondary-container": "#4b4585",
        "tertiary": "#914a00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b65e00",
        "on-tertiary-container": "#fffeff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e4dfff",
        "primary-fixed-dim": "#c5c0ff",
        "on-primary-fixed": "#150067",
        "on-primary-fixed-variant": "#3d24c5",
        "secondary-fixed": "#e4dfff",
        "secondary-fixed-dim": "#c6bfff",
        "on-secondary-fixed": "#180f50",
        "on-secondary-fixed-variant": "#443e7e",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb782",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703800",
        "background": "#fcf8ff",
        "on-background": "#1b1b23",
        "surface-variant": "#e4e1ed"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "container-max": "1280px",
        "container-padding": "40px",
        "gutter": "24px",
        "sidebar-width": "280px"
      },
      fontFamily: {
        "display": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "300" }],
        "label-xs": ["12px", { "lineHeight": "16px", "fontWeight": "300" }]
      }
    },
  },
  plugins: [],
}
